name: Deployment
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present        
        env:
          CI: false
      - name: Copy folder content recursively to vultr
        uses: garygrossgarten/github-action-scp@release
        with:
          local: out
          remote: /var/www/html/build_tph
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATEKEY }}
      - run: echo "🍏 This job status is ${{ job.status }}."
